### ISSUE TITLE
Allow privacy token to support either 2048 or 4096 RSA keys

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/privacy-proxy#1]
We should support different versions here.

**Comment by FredericJacobs** [comment]
Our recommendation for RSA is to keep 4096-bit keys. We can take a look at how to address performance concerns but I don't think reducing the security parameter size is the best option.

**Comment by chris-wood** [comment]
I support this relaxation. The actual long-term threat here only applies in very unrealistic or improbable scenarios. That said, having the version determine the key length is nice.

**Comment by enygren** [comment]
Is it worth then defining both a v1 (4096-bit key) and a v2 (same but 2048-bit key) within this draft, with some security considerations talking about the trade-offs?  (Or swapping the ordering of v1/v2?)

**Comment by chris-wood** [comment]
> Is it worth then defining both a v1 (4096-bit key) and a v2 (same but 2048-bit key) within this draft, with some security considerations talking about the trade-offs? (Or swapping the ordering of v1/v2?)

It probably wouldn't hurt, yeah. Clients that are willing to accept 2048-bit keys could choose to do so.
