### ISSUE TITLE
Check origin_name

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/privacy-proxy#100]
The Origin's challenge includes `origin_name`, but I don't think we have text which says that Clients must check that this name matches their expectation. Alternatively, the Origin could _not_ send this value, and the Client could reconstruct the `TokenChallenge` based on their expected `origin_name`.

**Comment by tfpauly** [comment]
Correct, the origin_name must be checked to ensure that it matches the origin that issued the challenge.

I don't think we should have the client reconstruct it, to avoid canonicalization issues.

**Comment by chris-wood** [comment]
> I don't think we should have the client reconstruct it, to avoid canonicalization issues.

I agree that checking is simpler, but won't either approach have to deal with canonicalization?

**Comment by tfpauly** [comment]
Yes, but I'd rather have the client check to see if things match and deal with canonicalization early on before issuing a request, rather than having the token issuance fail because the two parties disagreed on canonicalization.

**Comment by chris-wood** [comment]
Yep, agreed 👍

**Comment by tfpauly** [comment]
I think this is covered now in the auth scheme doc
