### ISSUE TITLE
Challenge and cookie cache

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/privacy-proxy#105]
Servers can offer multiple challenges in a WWW-Authenticate header to let the client fetch a pile of tokens for future spending. For tracking reasons, the lifetime of these should be bound to any cookie state associated with the origin. In particular, if the client wipes its cookies for the origin, then it should also clear any challenge state. It's possible for the server to encode client-specific information in the TokenChallenge.redemption_nonce, so we need to ensure this doesn't turn into a different type of tracking vector.

**Comment by tfpauly** [comment]
Good call-out!
