### ISSUE TITLE
Consider removing OHTTP dependency

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/privacy-proxy#124]
We currently borrow the public configuration structure from OHTTP, and the just use it for HPKE operations. This dependency doesn't buy us much at this point as we're not using OHTTP, so we might as well inline the structure definition.

**Comment by tfpauly** [comment]
I'd be happy to see this inlined and remove the dependency.

**Comment by tfpauly** [comment]
We could choose to either define specific algorithms supported by this token type, OR have the struct only have one field for each algorithm to not let the client choose in the request which it will use.
