### ISSUE TITLE
Relax rate-limited token challenge requirements 

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/privacy-proxy#147]
It seems totally reasonable for one to use the rate-limited token type to place an upper bound on tokens minted across origins, so the per-origin requirement seems overly restrictive. Same goes for  the interactive requirement, since that only has implications for the origin. In general, these should both be orthogonal to the type of token protocol.

**Comment by tfpauly** [comment]
I think removing the origin name would change the work for the attester quite a lot, and it's not clear to me what the client would send for it's anonymous origin name.

**Comment by chris-wood** [comment]
The attester is unaffected by this change. It computes the index just as before, but here the index is F(client secret, cross-origin secret) rather than F(client secret, per-origin secret). Everything else is the same. Clients would send special anonymous origin name that's akin to an "empty" origin.

**Comment by tfpauly** [comment]
Got it, so we just need to define the value to use for an "empty" origin. Makes sense!

**Comment by tfpauly** [comment]
Do this with #187
