### ISSUE TITLE
[geohash] Discuss handling of geohashes spanning boundaries

### ISSUE THREAD

**Issue by enygren** [tfpauly/privacy-proxy#156]
One major downside of geohashes is that they often span national or regional boundaries, this leaving the country ambigious.  This makes them hard to use "instead" of IP addresses.  More likely, they want to be used in-combination with IP addresses.  For example, using IP address to derive a country, but then using the geohash to refine the location within the country.

Additionally, proxies intending to preserve "country" in their source IP address (such as to prevent inclusion on lists of proxies allowing users to bypass geographic restrictions) may similarly wish to obtain the country information from an authenticated source (eg, a privacy token) and then refine the location within that country with the geohash.

**Comment by tfpauly** [comment]
Moving to geo IP entries: https://www.ietf.org/archive/id/draft-pauly-httpbis-geoip-hint-00.html
