### ISSUE TITLE
Nit: HTTP examples

### ISSUE THREAD

**Issue by mnot** [tfpauly/privacy-proxy#160]
In the issuance protocol, the examples use the path `/token-request`. Some may mistake this for a fixed path -- could you use something more obviously ephemeral, e.g., `/example-token-request-path` or `/my-token-request`? 

Also might be good to add prose about how the URL is found (sorry if this is addressed, I'm skimming).

**Comment by tfpauly** [comment]
@chris-wood FYI, this should be moved to https://github.com/ietf-wg-privacypass/base-drafts/issues

**Comment by chris-wood** [comment]
Moved to [this new issue](https://github.com/ietf-wg-privacypass/base-drafts/issues/96).

**Comment by mnot** [comment]
Thx!
