### ISSUE TITLE
Rate-Limited Tokens: "Origin Name Key" name is confusing

### ISSUE THREAD

**Issue by tlepoint** [tfpauly/privacy-proxy#169]
It is a little confusing to understand that “Origin Name Key” is an issuer-based key used to encrypt the origin name, but is not known/created by the Origin itself. Similarly, revealing the SHA256 of this key in the request to the attester is confusing because it seems to reveal the origin name, when it’s actually just an ID for an issuer key, which should be the same regarless of the origin. 

Maybe changing the name of this “Origin Name Key” to something that makes it clear that this is NOT created/known by the Origin, but by the Issuer instead, could help the reader.

**Comment by chris-wood** [comment]
This is now called the "Encap Key," so, closing!
