### ISSUE TITLE
Rate-Limited Tokens: Secrecy of public keys?

### ISSUE THREAD

**Issue by tlepoint** [tfpauly/privacy-proxy#170]
Section 2 states that 

> A public key chosen by the Client and shared only with the Attester.

> [...] whose public key is not shared with anyone.

This puts a strong emphasis on a notion of secrecy for the public keys, which is (1) unusual, as public keys are (always) assumed to be able to be made “public”, and (2) seems to indicate that the underlying signature scheme needs to have a notion of anonymity. 

If such secrecy of the public key is needed for security of the protocol, it should be emphasized, and the properties needed on the underlying signature scheme should be specified.

**Comment by tfpauly** [comment]
The problem here would be if the Issuer learned the public key during the token issuance interaction, because a stable public key could be used as an identifier for the client. We should clarify this.

**Comment by tfpauly** [comment]
We should clarify that the signature scheme shouldn't allow the public key to be reconstructed.
