### ISSUE TITLE
CONTRIBUTING.md has missing/broken link to mailing list

### ISSUE THREAD

**Issue by npdoty** [tfpauly/privacy-proxy#197]
Is there a mailing list for discussion of these work items, or is github issues the only/preferred venue?

CONTRIBUTING.md has a link to the `hint` mailing list, but I think that just wasn't filled in.

And if there's some way to get privacy issues labeled with `privacy-tracker` and picked up by the W3C apparatus, folks over at PING can more easily keep track of privacy issues and their status. Okay, I don't know if IETF groups are actually doing that, but just a thought.

**Comment by tfpauly** [comment]
Updated the links! Please check those out.
