### ISSUE TITLE
Expand key_id to 8 bytes

### ISSUE THREAD

**Issue by enygren** [tfpauly/privacy-proxy#2]
With key_id now being a hash of the public key, it would be preferable to switch the size of key_id to 8 bytes.  The chance of collisions with a  32-bit key_id with frequent rotations means that the key generation will need to track past keys to explicitly avoid collisions.  With a 64-bit key_id, accidental collisions is much more likely to be a non-issue.

**Comment by enygren** [comment]
(We should also define the encoding of the public key being hashed)

**Comment by chris-wood** [comment]
> We should also define the encoding of the public key being hashed

The public key is a DER-encoded SubjectPublicKeyInfo, which is fairly standard. 8 bytes seems fine here.

**Comment by tfpauly** [comment]
I think this is done?
