### ISSUE TITLE
Private Access Tokens should have an interactive mode

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/privacy-proxy#20]
Instead of being able to use cached tokens, there should also be a way to have the origin have a one-time challenge that binds a token to a particular session. This is important for high-value tokens that shouldn't be possible to harvest.

**Comment by chris-wood** [comment]
Making this interactive _should_ be pretty straightforward. In particular, redeemers can challenge clients with a per-token context, e.g.,

```
struct {
   opaque redeemer_nonce[32]; // 32 fresh random bytes
   uint64 timestamp;  // Seconds since UNIX epoch 
} TokenContext;
```

When generating a token request, clients can then form the message to be signed as: 

```
struct {
   opaque client_nonce[32]; // 32 fresh random bytes
   TokenContext context; // Copied from above
} TokenInput;

...

blinded_req, blind_inv = rsabssa_blind(ORIGIN_KEY, TokenInput)
```

`TokenContext` should be bound to the client session, e.g., discarded when the session goes away. @dvorak42, what do you think?

**Comment by dvorak42** [comment]
Yeah, this should work fine for single use context, though you'll need some period of validity that the client should be willing to sign the timestamp around (too long and the redeemer could be replaying a challenge from a different redeemer to get a signed token to use). There's then also the complexity of clock skew depending on how tight the bounds for the timestamp are.

**Comment by chris-wood** [comment]
I don't think skew is much of a problem here, since the redeemer is the one selecting the timestamp and then consuming it later on. The client should not need to use the timestamp in any way.

**Comment by dvorak42** [comment]
Ah I had been thinking about an attack where the redeemer is replaying another redeemer's challenge, but I think the client already binds the redeemer's identity to the signed token, so maybe that's not necessary?

**Comment by chris-wood** [comment]
I'll put up a PR in a bit and we can hash out the details :)
