### ISSUE TITLE
Discuss fallback options

### ISSUE THREAD

**Issue by smhendrickson** [tfpauly/privacy-proxy#22]
Mediator/issuer combinations may not be supported by all clients. We should choose and specify redeemer strategies to handle fallback. We should also add more detail into the example use cases.

**Comment by chris-wood** [comment]
I think we can close this one out. If the origin chooses an issuer that simply won't work with the client's preferred attester, then the issuance protocol can't run. Dealing with that scenario is an application-specific decision. @tfpauly, thoughts?

**Comment by tfpauly** [comment]
Yeah, I don't think we need to address this specifically — and it likely would be an architecture thing, not for rate-limited.
