### ISSUE TITLE
Rate-limit tokens has been adopted

### ISSUE THREAD

**Issue by martinthomson** [tfpauly/privacy-proxy#225]
At least according to https://github.com/ietf-wg-privacypass/draft-ietf-privacypass-rate-limit-tokens

**Comment by tfpauly** [comment]
Yes, removing this version now

**Comment by tfpauly** [comment]
https://github.com/tfpauly/privacy-proxy/commit/e063f3b80845f632d8f94a2e9c2d75cfc8b89ae6
