### ISSUE TITLE
Next hop aliases percent-encoding

### ISSUE THREAD

**Issue by bemasc** [tfpauly/privacy-proxy#232]
Domain names can also contain `"` and `%`, so I think the escaping rule has to be a bit more specific than just escaping commas, as indicated in the current text.

**Comment by tfpauly** [comment]
@bemasc would you mind moving your issues over the WG GitHub?

https://github.com/httpwg/http-extensions/labels/alias-proxy-status

**Comment by bemasc** [comment]
OK, moved to https://github.com/httpwg/http-extensions/issues/2357
