### ISSUE TITLE
Proxy PvD: Add more explicit information about proxies, not just URLs

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/privacy-proxy#243]
Instead of a bare list of proxy URLs, we should expand to have more information about the proxies. The most obvious attribute here is the protocol supported (CONNECT-UDP, CONNECT-IP, etc), but this could also define what this is used for. At 118, MoQ using proxies was brought up.

**Comment by DavidSchinazi** [comment]
+1. It would also be useful to know which version of HTTP the proxy supports (in terms of the client-to-proxy HTTP connection).

**Comment by DavidSchinazi** [comment]
Note that this issue isn't fully resolved by #244. We'd need to also add which underlying HTTP versions are supported by the proxy. One wrinkle that might make this more annoying is that the value might change per proxying protocol. For example, we have proxies that support proxy protocols `https-connect` and `connect-udp`, and that support underlying HTTP versions `HTTP/3` and `HTTP/2`, but such that `connect-udp` is only supported over h3 but not h2.

**Comment by tfpauly** [comment]
I think what's left here is all in #242
