### ISSUE TITLE
Clarify that configuration learned from a PvD can only constrain on-device configuration

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/privacy-proxy#260]
Clarify that configuration learned from a PvD can only constrain on-device configuration; if a device is only willing to proxy `example.com` traffic, a PvD can usefully constrain to only proxy `foo.example.com`, but cannot expand to also make clients proxy `bar.com`.

**Comment by ddragana** [comment]
The last paragraph of section 4. already explains this. I think we do not need more, or am I misunderstanding this issue?

**Comment by tfpauly** [comment]
Yes, you're right. I think this is OK to close.
