### ISSUE TITLE
Discuss related work, especially Privacy Pass

### ISSUE THREAD

**Issue by janaiyengar** [tfpauly/privacy-proxy#41]
... maybe in the introduction, maybe later. Is there any other relevant work that applies besides Privacy Pass?

**Comment by chris-wood** [comment]
If the Mediator doesn't send along the ANON_CLIENT_ID, then this basically reduces to Privacy Pass. (There is no stable client identifier.) Maybe that's all we say about this? 🤷

**Comment by tfpauly** [comment]
My notes for the differences:

Challenge-based, proves you’re online/valid right now, and not harvested
Per-origin rate limiting — a better solution for captchas, makes it possible to do metered paywalls
Publicly verifiable — no need to loop back to the issuer, very cheap for the origin
