### ISSUE TITLE
Normatively define the mapping from lat/lon to/from Sec-CH-Geohash

### ISSUE THREAD

**Issue by jyasskin** [tfpauly/privacy-proxy#77]
https://tfpauly.github.io/privacy-proxy/draft-pauly-httpbis-geohash-hint.html says `Sec-CH-Geohash` holds "an encoded Geohash", but the only definition is in an informative reference to https://en.wikipedia.org/wiki/Geohash.

**Comment by tfpauly** [comment]
Moving to geo IP entries: https://www.ietf.org/archive/id/draft-pauly-httpbis-geoip-hint-00.html
